import Footer from './Footer'
import Header from './Header'
import './globals.css'

export const metadata = {
  title: 'Covid19',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className=''>
        <header>
          <Header />
        </header>

        <main>
          {children}
        </main>

        <footer>
          <Footer />
        </footer>

      </body>
    </html>
  )
}